version: '3.7'

services:
  nexus:
       image: sonatype/nexus3
       ports: 
       - "8081:8081"
       volumes:
       - "/root/docker_compose/nexus/data:/nexus-data"
       environment:
       - "INSTALL4J_ADD_VM_PARAMS=-Xms128m -Xmx512m -XX:MaxDirectMemorySize=128m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"