version: '3.7'


services:

  redis:
     image: redis
     ports:
       - "6379:6379"
  registor:
      image: yecheng007/registrator
      volumes: 
         - "/var/run/docker.sock:/tmp/docker.sock"
      network_mode: "host"
      depends_on:
         - consul_server
         - consul_local
      command: /bin/registrator --ip=47.115.214.28 --localDiscovery=consul://47.115.214.28:8501 consul://47.115.214.28:8500

  mysql:
      image: mysql:latest
      volumes:
        - "/root/mysql:/var/lib/mysql"
        - "/root/myetc/my.cnf:/etc/my.cnf"
      environment:
         MYSQL_ROOT_PASSWORD: 123456yd
      ports:
         - "3306:3306"
  consul_local:
      image: consul
      ports:
          - "8501:8500"
          - "8302:8301"
      command: agent -server -bootstrap-expect 1 -node=consul_local -ui -bind 0.0.0.0 -client 0.0.0.0

  consul_server:
        image: consul
        ports:
           - "8500:8500"
           - "8301:8301"
        command: agent -server -bootstrap-expect 1 -ui -node consul_server -bind 0.0.0.0 -client 0.0.0.0


