version: '3.7'

services:
  redis:
     image: redis
     ports:
       - "6379:6379"
  registor:
      image: gliderlabs/registrator
      volumes: 
         - "/var/run/docker.sock:/tmp/docker.sock"
      network_mode: "host"
      depends_on:
         - consul_client
         - consul_server
      command: --ip=120.77.221.92  consul://120.77.221.92:8500

  mysql:
      image: mysql:latest
      volumes:
        - "/root/mysql:/var/lib/mysql"
      environment:
         MYSQL_ROOT_PASSWORD: 123456yd
      ports:
         - "3306:3306"

  consul_client:
       image: consul
       depends_on:
         - consul_server
       command: agent -node=consul_client  -join consul_server

  consul_server:
        image: consul
        ports:
           - "8500:8500"
           - "8301:8301"
        command: agent -server -bootstrap-expect 1 -ui -node consul_server -bind 0.0.0.0 -client 0.0.0.0


