version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
       - "80:80"
    networks:
      - nginx

  ykv_8085:
     image: yc/ykv_8085
     ports:
      - "8085:8085"
     networks:
      - nginx

  ykv_8086:
      image: yc/ykv_8086
      ports:
        - "8086:8086"
      networks:
        - nginx
    