version: '3.7'


networks:
  nginx:
    external: true
    
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "/root/docker_compose/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/root/docker_compose/nginx/dynamic:/etc/nginx/conf.d/dynamic"
    ports:
       - "80:80"
    networks:
      - nginx

    