version: '3.7'


networks:
  nginx:
    external: true
    
services:
  nginx:
    image: nginx
    volumes:
      - "/root/docker_compose/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
       - "80:80"
    networks:
      - nginx

    