version: '3.7'
    
services:
  nginxFour:
    container_name: nginxFour 
    image: nginx
    volumes:
      - "/root/code/docker_compose/nginx/four/nginx.conf:/etc/nginx/nginx.conf"
      - "/root/nginx/four:/var/log/nginx"
    ports:
       - "81:81"