version: '3.7'


networks:
  nginx:
    external: true
    
services:
  nginxFour:
    container_name: nginxFour 
    image: nginx
    volumes:
      - "/root/docker_compose/nginx/four/nginx.conf:/etc/nginx/nginx.conf"
      - "/root/logs/four:/var/log/nginx"
    ports:
       - "81:81"