version: '3.7'

services:

  namesrv:
       image: rocketmqinc/rocketmq
       ports: 
         - "9876:9876"
       environment:
         - "JAVA_OPT_EXT=-server -Xms64m -Xmx100m -Xmn32m"
       command: sh mqnamesrv

  rmq_console:
       image: styletang/rocketmq-console-ng
       ports:
        - "9877:8080"
       environment:
        - "JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -server -Xms32m -Xmx64m -Xmn64m"

