version: '3.7'

services:

  registor:
      image: gliderlabs/registrator
      volumes: 
         - "/var/run/docker.sock:/tmp/docker.sock"
      depends_on:
         - consul_server
      command: /bin/registrator -ip=${IP} consul://${IP}:8500

  mysql:
      image: mysql:latest
      volumes:
        - "/root/mysql:/var/lib/mysql"
        - "${path}/docker_compose/myetc/my.cnf:/etc/my.cnf"
      environment:
         MYSQL_ROOT_PASSWORD: 123456yd
      ports:
         - "3306:3306"

  consul_server:
        image: consul
        ports:
           - "8500:8500"
           - "8301:8301"
        command: agent -server -bootstrap-expect 1 -ui -node consul_server -bind 0.0.0.0 -client 0.0.0.0

  namesrv:
       image: rocketmqinc/rocketmq
       ports: 
         - "9876:9876"
       environment:
         - "JAVA_OPT_EXT=-server -Xms64m -Xmx100m -Xmn32m"
       command: sh mqnamesrv
    
  broker:
       image: rocketmqinc/rocketmq
       depends_on:
         - namesrv
       ports:
         - "10911:10911"
         - "10909:10909"
       volumes:
         - "${path}/docker_compose/rmq/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf"
       environment:
         - "NAMESRV_ADDR=namesrv:9876"
         - "autoCreateTopicEnable=true"
         - "JAVA_OPT_EXT=-server -Xms64m -Xmx100m -Xmn32m"
       command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf
  rmq_console:
       image: styletang/rocketmq-console-ng
       ports:
        - "9877:8080"
       environment:
        - "JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -server -Xms32m -Xmx64m -Xmn64m"
